# Site settings
title: "Tsz Kin Lam: Researcher at the University of Edinburgh"
description: "Tsz Kin Lam: Researcher at the University of Edinburgh"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tsz Kin Lam"
resume_title:                   "AI Researcher in NLP and Speech"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kintz0911@gmail.com"

resume_header_intro: "
  <p>
    Hello! I am a researcher and a GAIL Fellow at the University of Edinburgh, where I work closely with <a href='https://sites.google.com/view/alexandra-birch/home' style='color: black'>Alexandra Birch</a>, <a href='https://homepages.inf.ed.ac.uk/bhaddow/' style='color: black'>Barry Haddow</a>, members from the machine translation team and CSTR. I earned my BSc in Physics from HKUST, Master and PhD at Heidelberg University in Germany, where I was fortunate to be supervised by <a href='https://www.cl.uni-heidelberg.de/statnlpgroup/members/riezler/' style='color: black'>Prof. Stefan Riezler</a>.<br>

    <br>My current research interest is around speech LLM, post-training and human-agent collaboration. 
  </p>
  <p style="text-align: center;">I am now in the job market. Please get in touch if I fit well in your team!</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_grant:           true
resume_section_service:         true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/ondrejklejch"
  # resume_twitter_url:           "http://twitter.com/ondrejklejch"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/tklam"
  resume_googlescholar_url:     "https://scholar.google.com/citations?user=ii8kohwAAAAJ&hl=en"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://www.ondrejklejch.cz"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
