# Professional Service
- role: "Organizer"
  name: "IWSLT (Offline Track) 2024-2025"

- role: "Area Chair"
  name: "ACL Rolling Review (ARR)"

- role: "Reviewer"
  name: "ARR, ICASSP, INTERSPEECH, TACL, TALLIP, TASLP"
